### PR TITLE
fix: error forwarding in startStreaming

### LINKED ISSUE #23: StartStreaming errors not passed to the caller
# 🐞 Bug Report

### Affected Services [**REQUIRED**]

 The issue is located in: 

### Is this a regression?

 No

### Description and Minimal Reproduction [**REQUIRED**]

Make sure that the rtsp is NOT running.

Start streaming:
```
$ curl -X PUT -d '{                                                                              
    "StartStreaming": {
      "InputImageSize": "640x480",
      "OutputVideoQuality": "5"
    }
}' http://localhost:59882/api/v2/device/name/Logitech_StreamCam-4B17BE45/StartStreaming
{"apiVersion":"v2","statusCode":200}
```

This returns 200 OK as if the requested operation was successful. If this HTTP request is just meant to accept the the operation and run it asynchornously, the response code should be [202 Accepted](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/202)

Logs:
```
level=INFO ts=2022-05-19T11:48:31.864475627Z app=device-usb-camera source=driver.go:536 msg="start video streaming for device Logitech_StreamCam-4B17BE45"
level=ERROR ts=2022-05-19T11:48:32.774545384Z app=device-usb-camera source=driver.go:524 msg="the video streaming process for device Failed Finish FFMPEG ([-nostats -loglevel 0 -y -s 640x480 -i /dev/video0 -qscale 5 -f rtsp -hls_list_size 0 rtsp://localhost:8554/stream/Logitech_StreamCam-4B17BE45]) with exit status 1 message   has stopped, error: %!s(MISSING)"
```

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment
**Deployment Environment:**

**EdgeX Version [**REQUIRED**]:**

**Anything else relevant?**

### PR DESCRIPTION
**Pull request by ChristianDarr-personal**
Closes #23 

**If your build fails**  due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/edgex-go/blob/main/.github/Contributing.md

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [x] I am not introducing a new dependency (add notes below if you are)
- [ ] I have added unit tests for the new feature or bug fix (if not, why?)
- [x] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
- [ ] I have opened a PR for the related docs change (if not, why?)
  <link to docs PR>

## Testing Instructions

Make sure that the service is not streaming. Then, execute the startStreaming command, making sure that it should create an error (invalid input, etc). The rest response should be an error code with a description of the error.

### CODE REVIEW

File: internal/driver/driver.go [hunk 1]
```diff
@@ -633,23 +634,31 @@ func (d *Driver) startStreaming(device *Device) errors.EdgeX {
...
+				startErrs <- errors.NewCommonEdgeX(errors.KindServerError, fmt.Sprintf("failed to stop video streaming for device %s, error: %s", device.name, err), err)
+				d.wg.Done()
+				return
 			}
 			d.lc.Debugf("the video streaming process for device %s has stopped", device.name)
 			d.wg.Done()
 			return
 		}
 	}()
+	if startErrs != nil {
```
Comment (lenny-goodell) [inline internal/driver/driver.go]: Check for != nil is not needed since the channel was created above.

File: internal/driver/driver.go [hunk 2]
```diff
@@ -633,23 +634,31 @@ func (d *Driver) startStreaming(device *Device) errors.EdgeX {
...
+		return <-startErrs
+	}
```
Comment (lenny-goodell) [inline internal/driver/driver.go]: This will block forever if no errors. Needs a timeout, so something like this. Need to determine appropriate timeout value  
```suggestion
        for {
          select {
          case <-time.After(time.Second)
             break
          case err  <-startErrs
	     return err
        }
```

File: internal/driver/driver.go [hunk 3]
```diff
@@ -633,23 +634,31 @@ func (d *Driver) startStreaming(device *Device) errors.EdgeX {
...
 			device.StopStreaming(err)
-			d.lc.Errorf("the video streaming process for device %s has stopped, error: %s", device.name, err)
+			d.lc.Debugf("the video streaming process for device %s has stopped", device.name)
+			startErrs <- errors.NewCommonEdgeX(errors.KindServerError, fmt.Sprintf("the video streaming process for device %s has stopped, error: %s", device.name, err), err)
 			d.wg.Done()
 			return
 		case <-device.ctx.Done():
 			if err := device.transcoder.Stop(); err != nil {
 				d.lc.Errorf("failed to stop video streaming for device %s, error: %s", device.name, err)
+				startErrs <- errors.NewCommonEdgeX(errors.KindServerError, fmt.Sprintf("failed to stop video streaming for device %s, error: %s", device.name, err), err)
```
Comment (lenny-goodell) [inline internal/driver/driver.go]: I don't think this is needed. Should just log it since it isn't a start error.

File: internal/driver/driver.go [hunk 4]
```diff
@@ -633,23 +634,31 @@ func (d *Driver) startStreaming(device *Device) errors.EdgeX {
 		return errors.NewCommonEdgeX(errors.KindServerError, fmt.Sprintf(
 			"failed to start video streaming for device %s", device.name), err)
 	}
+	startErrs := make(chan errors.EdgeX)
```
Comment (lenny-goodell) [inline internal/driver/driver.go]: Always have buffer of at least one
```suggestion
	startErrs := make(chan errors.EdgeX, 1)
```

File: internal/driver/driver.go [hunk 5]
```diff
@@ -633,23 +634,31 @@ func (d *Driver) startStreaming(device *Device) errors.EdgeX {
...
 	d.wg.Add(1)
 	go func() {
 		select {
 		case err := <-errChan:
 			device.StopStreaming(err)
-			d.lc.Errorf("the video streaming process for device %s has stopped, error: %s", device.name, err)
+			d.lc.Debugf("the video streaming process for device %s has stopped", device.name)
```
Comment (lenny-goodell) [inline internal/driver/driver.go]: Why Debug and not error?

**Review by lenny-goodell — CHANGES_REQUESTED** [review]

**Review by lenny-goodell — APPROVED** [review]
LGTM

**Review by farshidtz — APPROVED** [review]
Looks good. Thanks for the fix!

I tested and could not reproduce the bug described in #23. It adds 1s delay to start requests, which is by design.

```
$ time curl -X PUT -d '{                                                                              
    "StartStreaming": {
      "InputImageSize": "640x480",
      "OutputVideoQuality": "5"
    }
}' http://localhost:59882/api/v2/device/name/example-camera/StartStreaming
{"apiVersion":"v2","statusCode":200}

real	0m1.011s
user	0m0.004s
sys	0m0.004s

$ snap stop edgex-device-usb-camera.rtsp-simple-server 
Stopped.

$ time curl -X PUT -d '{                                                                              
    "StartStreaming": {
      "InputImageSize": "640x480",
      "OutputVideoQuality": "5"
    }
}' http://localhost:59882/api/v2/device/name/example-camera/StartStreaming
{"apiVersion":"v2","message":"request failed, status code: 500, err: {\"apiVersion\":\"v2\",\"message\":\"error writing DeviceResourece StartStreaming for example-camera -\\u003e the video streaming process for device example-camera has stopped, error: Failed Finish FFMPEG ([-nostats -loglevel 0 -y -s 640x480 -i /dev/video0 -qscale 5 -f rtsp -hls_list_size 0 rtsp://localhost:8554/stream/example-camera]) with exit status 1 message   -\\u003e Failed Finish FFMPEG ([-nostats -loglevel 0 -y -s 640x480 -i /dev/video0 -qscale 5 -f rtsp -hls_list_size 0 rtsp://localhost:8554/stream/example-camera]) with exit status 1 message  \",\"statusCode\":500}","statusCode":500}

real	0m0.518s
user	0m0.000s
sys	0m0.007s
```

**Review by ajcasagrande — APPROVED** [review]
